### ISSUE TITLE
[Spike] C4GT - Devops Journey

### ISSUE THREAD

**Issue by karntrehan** [Code4GovTech/server#103]
### Community:

- Contributor lands on C4GT website / github
- Contributor joins discord
- Contributor links github to discord
- Orgs add C4GT app to their github repo
- Orgs add C4GT Community label to their tickets
- Contributor sees list of community tickets on website
- Contributor comments on community tickets
- Contributor raises PR on community tickets
- Community ticket is closed via PR merge
- Contributor gets points
- Contributor gets badges and certificates basis points

### Dedicated mentorship program:

- Contributor lands on C4GT website / github
- Contributor joins discord
- Contributor links github to discord
- Orgs nominate tickets for DMP
- C4GT team adds DMP tickets to DMP Website
- Contributor sees DMP tickets on DMP website
- Contributor submits proposals for DMP tickets
- Contributor gets selected
- Contributor raises PR on DMP ticket
- DMP ticket is closed via PR merge
- Contributor gets points

## Current devops landscape: 
* Discord Bot - Jenkins (Staging: Does not exist, Prod: Manual) - https://github.com/Code4GovTech/discord-bot
* Server repo - Docker (Staging: Manual, Prod: Manual) - https://github.com/Code4GovTech/server
* DMP CMS Cron - Docker (Staging: Auto, Prod: Manual) - https://github.com/Code4GovTech/DMP-CMS-Backend-CRON
* DMP CMS API - Docker (Staging: Auto, Prod: Manual) - https://github.com/Code4GovTech/DMP-CMS-Backend-API
* DMP CMS Frontend - Docker (Staging: Auto, Prod: Manual) - https://github.com/Code4GovTech/dmp-documentation
* Website - Wix
* Devops v2 - https://github.com/Code4GovTech/devops-v2

## Requirements: 

1. Monitoring and alerting (P0 - In the next few days) - Ticket: https://github.com/Code4GovTech/C4GT/issues/431
2. Auto-deployment to staging and prod
3. Uniformity (Jenkins vs Github CI)
4. Cleanup of deployment structure (Ex: discord bot vault in different server)

## Journey of DevOps

Pre-prepare

- [x] Add predefined workflows to all the repository (build process + release process)
- [x] Provision Infrastructure for C4GT (Azure) 
- [x] Configure new domain to point to new machine
- [x] Setup the devops pipeline on new machine (grafana, prometheus, webhook server, uptime kuma, + custom services)
- [x] Health Checks to verify if everything is working fine

Staging

- [x] Add predefined workflows to all the repository (build process + release process)
- [x] Provision Infrastructure for C4GT (Azure) 
- [x] Stop the staging servers and migrate data to new machine ~ 30 mins
- [x] Configure domain to point to new machine
- [x] Setup the devops pipeline on new machine (grafana, prometheus, webhook server, uptime kuma, + custom services)
- [x] Health Checks to verify if everything is working fine

Production

- [ ] Add predefined workflows to all the repository (build process + release process)
- [ ] Provision Infrastructure for C4GT (Azure) 
- [ ] Stop the staging servers and migrate data to new machine ~ 30 mins
- [ ] Configure domain to point to new machine
- [ ] Setup the devops pipeline on new machine (grafana, prometheus, webhook server, uptime kuma, + custom services)
- [ ] Health Checks to verify if everything is working fine

**Comment by karntrehan** [comment]
@singhalkarun working on adding kong to central pipeline.

**Comment by MohitNSamagra** [comment]
- Kong added but not configured for our services

**Comment by MohitNSamagra** [comment]
- Aakaash to start testing - metrics to show up(kong) for dev

**Comment by MohitNSamagra** [comment]
- Testing blocked currently on @karntrehan @singhalkarun
