### ISSUE TITLE
New issue tickets on Community not being picked up

### ISSUE THREAD

**Issue by AbhimanyuSamagra** [Code4GovTech/server#170]
https://github.com/Code4GovTech/C4GT/wiki/C4GT-Community-Campaign-1

you can find all the tickets that are not showing up listed above

@jaanbaaz to check by 19th Nov

**Comment by AbhimanyuSamagra** [comment]
Waiting for @karntrehan for his diagnosis

**Comment by AbhimanyuSamagra** [comment]
Add label again on all the tickets

**Comment by MohitNSamagra** [comment]
https://github.com/PSMRI/AMRIT/issues
