### ISSUE TITLE
DMP Website is down

### ISSUE THREAD

**Issue by AbhimanyuSamagra** [Code4GovTech/server#172]
@jaanbaaz the entire DMP website is down, hypothesis is because of the shift from Supabase to Postgres

**Comment by AbhimanyuSamagra** [comment]
@jaanbaaz @rohan27 to bring to production by 20th November,

**Comment by AbhimanyuSamagra** [comment]
@jaanbaaz to wait for @karntrehan as the base URL needs to be changed

**Comment by AakashSatpute119** [comment]
Website is working now.
