### ISSUE TITLE
[Dasboard] Real time change in visualized data of older program dashboard

### ISSUE THREAD

**Issue by omkar309** [Code4GovTech/server#27]
Requirement:
The data of the [older program dashboard](https://dashboard.c4gt.samagra.io/dashboard/9-community-program-metrics) is not changing when changes are made to the program tickets. This needs to be fixed.

Acceptance criteria:
It should happen automatically and as real time as possible.

**Comment by KDwevedi** [comment]
- [ ] @KDwevedi to also handle renaming of labels

**Comment by omkar309** [comment]
@karntrehan to verify this. And we can move this to done.
