### ISSUE TITLE
[C4GT dashboard] Program Dashboard fixes

### ISSUE THREAD

**Issue by omkar309** [Code4GovTech/server#30]
**Requirement:**
Data inconsistency has been observed in the following KPI cards on the [program dashboard](https://dashboard.c4gt.samagra.io/public/dashboard/33b5cef6-c162-45f8-9adf-e4006148b9f0)
1. Active contributors
2. Super contributors
3. Inactive contributors
4. College chapter metrics

**Acceptance criteria:**

- [x] Kanav to check the pull requests that have gotten merged but are not being detected and provide fix
- [x] Currently the dashboard shows 39 active contributors, but there are 55 PR merge requests, Kanav to look into it and provide fix
- [x] Kanav to look into college chapter metrics and no. of inactive contributors count to ensure data consistency

**Reason:**
Data displayed on program dashboard should be accurate and should change dynamically.

**Comment by omkar309** [comment]
- [ ] Add filter of beginner on Program Dashboard

**Comment by omkar309** [comment]
- [ ] Chapter no. and table to be corrected

**Comment by omkar309** [comment]
- [ ] 'Remove Beginner' filter to remove beginner count on all the cards
- [ ] Total contributor count on the dashboard is 642, which is less than no. of contributors on discord

**Comment by omkar309** [comment]
- [ ] Identify the bug affecting the engaged contributors count

**Comment by karntrehan** [comment]
@omkar309 and @Y3ABHISHEK currently testing this.
