### ISSUE TITLE
[C4GT discord bot] Issuance of certificates as VC

### ISSUE THREAD

**Issue by omkar309** [Code4GovTech/server#34]
**Requirement:**

1. For community program- A certificate should be issued to the contributor upon completion of a milestone based on DPG points in the form of a verifiable credential
2. For DMP- A certificate should be issued to the contributor at the end of the program upon completion of the project in the form of a verifiable credential
3. Issuing participation certificate in the form of VC to all those who send proposals under DMP

**Acceptance criteria:**

1. The user will be able to generate the certificate using the discord bot by entering a command- “!my_certificate” or need to have a separate channel for this in the server
2. The bot will generate a link for the certificate, upon clicking which a new tab will open up with with the certificate displayed on it
3. There will be an option to download the PDF of the certificate
4. The characteristics of the certificate are as follows-

![Image](https://github.com/Code4GovTech/server/assets/124027239/b584721e-7d19-442f-9790-7ef6143cd931)

5. Upon scanning QR code following will appear-

![Image](https://github.com/Code4GovTech/server/assets/124027239/9229971e-7cce-4e1b-9673-16d4c4ce737b)

**Reason:**
Every milestone is a one time event that any contributor will achieve through their C4GT journey. That event can be captured as a VC and is feasible.

**Comment by KDwevedi** [comment]
closing this issue as it is done
