### ISSUE TITLE
[Discord bot] VC cert. and snippet channel and buttons-P1

### ISSUE THREAD

**Issue by omkar309** [Code4GovTech/server#37]
Goal:
Issuing certificates to contributors (both community program and DMP), mentors (for DMP) and organizations (for DMP)

User Type: Community Contributor

Usecase:

- [x] Registered contributors should be able to access the channel "Certificates and DPG profile" on the C4GT discord server
- [x] Contributor can see two buttons on entering the""Certificates and DPG profile"" channel-

1. My certificate
2. My DPG profile

**Comment by KDwevedi** [comment]
Changes yet to be pushed as connected features are yet to be completed.

**Comment by karntrehan** [comment]
Tested by Omkar. Working as expected. Closing now.
