### ISSUE TITLE
[Bug] Verified Contributor badge not displayed on Discord and on website

### ISSUE THREAD

**Issue by omkar309** [Code4GovTech/server#46]
**Requirement:**
Currently many users can not see the verified contributor badge even after they have done the registration process multiple times. This bug needs to be fixed.

**Acceptance criteria:**

1. User registers as a contributor for C4GT, user enters C4GT server, clicks on authorize button, registers himself/herself and links their github ID with discord ID.
2. After that, on going to the 'Channels and Roles' channel on the server they can view their profile and the 'Verified contributor' badge assigned to them
3. And if they have merged atleast 1 PR of 5 points or more, the 'DiscordXGitHub' badge should be displayed under activity badges against the user's name on the leaderboard on the website.

**Reason:**
This bugs hinders community user experience by creating confusion. So needs fixing at the earliest.

**Comment by KDwevedi** [comment]
closing this issue as it is done
