### ISSUE TITLE
[Program Dashboard] Modifications for Feb for GovTech

### ISSUE THREAD

**Issue by omkar309** [Code4GovTech/server#47]
**Requirement:**

- [x] Date filter on overall dashboard to filter out PRs merged in the month of February 2024
- [x] Additional columns in the 'Issue Tickets' table in the program dashboard
  - [x] PRs raised
  - [x] Total engaged contributors (Count of comments by unique users)
  - [x] Mentor (Assigned mentor's GitHub ID and Discord ID)
  - [x] Mentor Activity (Count of total comments by the mentor)
  - [x] Assigned contributor (Assigned contributor's GitHub ID and Discord ID)
  - [x] Assigned contributor's total DPG points (Filterable by months)

**Acceptance criteria:**

1. The date filter should work on relevant viz. cards, priority being the 'PRs merged' column of the Issue Tickets table on the [program dashboard](https://dashboard.c4gt.samagra.io/public/dashboard/33b5cef6-c162-45f8-9adf-e4006148b9f0?exclude_by_complexity=Beginner)
2. Additional columns should be visible in the table names 'Issue tickets' on the program dashboard as mentioned in the requirements and get filtered by changing the date filter.
3. By clicking on the GitHub ID and Discord ID of the contributor and mentor, the GitHub profile and the Discord DM should open up in a new tab of the browser respectively.

**Reason:**

1. This is being done to make February a window where a spike in the community can be created to generate momentum for DMP 2024.
2. The incentive is that for the goodies that a contributor usually gets on achieving 100 DPG points, can get the same goodies if they solve issue tickets, get PRs merged and earn 50 points in February itself. Points earned before 1st Feb 2024 and after 29th Feb 2024 won't be taken into consideration.

**Comment by omkar309** [comment]
After discussing with @KDwevedi 
Instead of adding a date filter we will be creating another table named 'Feb4GovTech' that will capture data only for Feb 2024 i.e. from 00:00 1st Feb 2024 to 23:59 29th Feb 2024
But these columns and date filter are required for 'Issue Tickets' column as these metrics are to be tracked for the overall community at all times.
So after DMP 2024 we will subsume the 'Feb4GovTech' and 'Issue tickets' tables and make then into one table.

**Comment by karntrehan** [comment]
Sheet being created and shared daily. 

Dashboard clarification on date filter awaited from PT / @omkar309.

**Comment by omkar309** [comment]
Clear written requirements awaited from PT

**Comment by omkar309** [comment]
Data in excel sheet being provided to PT daily. PT internal handover happening so this is blocked on PT at the moment.

**Comment by omkar309** [comment]
Will be picked after 1st March, Kanav moving to BHASAI

**Comment by omkar309** [comment]
PT requirements mentioned here: https://docs.google.com/spreadsheets/d/1ht0kAGXNnsTku947RzEmeXlWvk5eZTJ5ctlI4Gkmggw/edit#gid=1153816844

**Comment by KDwevedi** [comment]
# Requirements:
## Additional Cards:
### Issue Tickets
- Issue URL: from ccbp_tickets table
- Status: from ccbp_tickets table
- Organisation: from ccbp_tickets table
- Mentor Github: from ccbp_tickets table
- Mentor Discord: join from contibutors_discord using contributors_registration
- Mentor comments: join on ticket_comments
- Issue Author Github: Add additional column in ccbp_tickets 
- Issue Author Discord: join from contibutors_discord using contributors_registration
- Issue Author comments: join on ticket_comments
- PR Count: join on connected PRs
- PR URLs: join on connected PRs
- Unique Commenters: join on ticket_comments
- Is Assigned: Add additional column in ccbp_tickets 
- Assignee Github: Add additional column in ccbp_tickets 
- Assignee Discord: join from contibutors_discord using contributors_registration

### Assignee Points

- Assignee
- Tickets Assigned (list of urls)
- DPG points

## Adding a Date Filter:
- [ ] All macro metrics under 'C4GT Community Dashboard', 'College Chapter Level Metrics', 'Independent Contributors' headers on the metabase dashboard.
- [ ] Engaged, Active, Super, Inactive, Lapsed contributors under 'College Chapter Details'
- [ ] Mentor comments, PR counts, unique commenters under the previously modified Issue Tickets card
- [ ] DPG points under the previously modified Assignee Points card.

### Behaviour

**Comment by omkar309** [comment]
**Details about the new table that needs to be created on the dashboard right after the Issue tickets table**

The following columns should be added as part of a new table on which the date range filter should be applied
Table name: Contributor points
Columns: Serial No. , GitHub Username, Discord Username, Total points, Total PRs raised, Total PRs merged

**Comment by KDwevedi** [comment]
@sasi2312 
- [x] DPG Points Table is Completed to be tested
- [ ] Date Filter Change by Today

---

Creation date of first ticket listed by the org is taken as cut-off date for the date filter on organisation count question.

Creation date of chapter role on discord is taken as cut-off date for the date filter on chapter count and related questions.

- [ ] @sasi2312 to have complete clarity on implementation details wrt to these changes by EOD
  - [ ] Evaluate DB structure wrt organisation listing
  - [ ] Propose necessary changes for dashboard
  - [ ] Familiarise with discord [Roles](https://discordpy.readthedocs.io/en/stable/api.html#role) in discord.py API reference
  - [ ] Look at [listeners](https://github.com/Code4GovTech/discord-bot/blob/main/cogs/listeners/role_events_cog.py) in discord bot responsible for filling chapter related data
  - [ ] look at `chapters` table on supabase
  - [ ] Evaluate necessary changes for dashboard

**Comment by sasi2312** [comment]
- Have some doubts to add datefilters in  super contributors ..now clarified from @KDwevedi .Going to be work on that
- Add datefilter in Issue Ticket analysis is completed

**Comment by karntrehan** [comment]
@sasi2312 to add date filter on super contributor. To be done today.

**Comment by MohitNSamagra** [comment]
- Problem displaying total potential contributors - to be checked by @sasi2312 
- List of super contributors to be shared by @sasi2312 - to be tested by @MohitNSamagra

**Comment by sasi2312** [comment]
1. Problem displaying total potential contributors - completed from my side pls check and update
2.I have attached the list of super contributors below pls check on this
[super_contributors_Records_dashboard (1).csv](https://github.com/Code4GovTech/server/files/15022951/super_contributors_Records_dashboard.1.csv)

**Comment by MohitNSamagra** [comment]
- @sasi2312 / @MohitNSamagra to get list of super contributors with PR details

**Comment by MohitNSamagra** [comment]
- List of super contributors checked against list of 13 sent in Feb. 15 are showing up, which is fine and should be correct.
- Checked all 15 in Supabase and all have merged at date in feb with 'Low' complexity tickets
- But, vilol-04 's name not appearing in this list of 15 even though PR was merged in feb. To be checked.

**Comment by MohitNSamagra** [comment]
- vilol-04 not appearing as they became super contributor in dec 2023. The filter only picks up users who became super contributors in the time frame set

**Comment by karntrehan** [comment]
@VedantKhairnar @Y3ABHISHEK @MohitNSamagra @karntrehan to do end to end test of Dashboard and create issue tickets.

**Comment by MohitNSamagra** [comment]
- Issues to be scoped in the next week @MohitNSamagra
