### ISSUE TITLE
[C4GT classroom] Check classroom points on supabase

### ISSUE THREAD

**Issue by omkar309** [Code4GovTech/server#66]
Requirement:
It has been noticed that the points of contributors present on GitHub classroom is in different than the points stored in our supabase table.
@sasi2312 to check once if the points visible using GitHub classroom API are the same as stored in our supabase table.

Reason:
To avoid any data discrepancy.

List of contributors who're not able to see their names on the community leaderboard or the no. of their DPG points shown is incorrect: https://docs.google.com/spreadsheets/d/1YxMSWc_u7wIJ0T15o0y30QngCEL7ASO4FPWuuA0RIco/edit?usp=sharing

**Comment by karntrehan** [comment]
Github API is failing - 500. Was working fine previously. @sasi2312 to check.

**Comment by MohitNSamagra** [comment]
- No documentation for 500
- Support request raised

**Comment by sasi2312** [comment]
I have tried with this endpoint
https://api.github.com/assignments/{id}/accepted_assignments ---- it working.

- The response we get from this api is slightly differ from older one.
- Need to change the existing cronjob @KDwevedi @MohitNSamagra

**Comment by MohitNSamagra** [comment]
- Checking null (points) users(Mohit)

**Comment by sasi2312** [comment]
**These user have grade as NULL:** @MohitNSamagra @KDwevedi 

- 'IAlgorithmia',
-  'RiyaRaj28', 
- 'SaumyaSamagra', 
- 'Shruti3004', 
- 'Ranjanmangla1',
-  'karntrehan', 
- 'Omkar309',
-  'Param1304',
-  'Vaibhavn07',
-  'PraveenRepswal',
-  'Sayan2908', 
- 'sujanMidatani7', 
- 'simran142002', 
- 'limitlessBrain1', 
- 'pankaj-2503', 
- 'Poojithaduggireddy', 
- 'kabirrajsingh', 
- 'mohdyasirkn', 
- 'KK1215'

**Comment by KDwevedi** [comment]
@sasi2312 
Can you edit the above comment and add the total count of individual assigments that you're getting?

**Comment by karntrehan** [comment]
Null mapped to 0. @MohitNSamagra to check and confirm.

**Comment by MohitNSamagra** [comment]
- Out of the 10 github usernames, only 2 exist(Shruti and Riya)

**Comment by MohitNSamagra** [comment]
- @sasi2312 to check API docs for null values
- @MohitNSamagra to check with original list of contributors

**Comment by karntrehan** [comment]
Complaints checked. Found 49 complaints where classroom is completed, but DPG points are less than 100. 

@karntrehan to discuss with Yash / Chakshu on this.

**Comment by MohitNSamagra** [comment]
- To be tested: 'Huzaifmalik' has incorrect points on leaderboard @MohitNSamagra
- @KDwevedi @karntrehan: SQL updates for MV for leaderboard

**Comment by MohitNSamagra** [comment]
- Huzaif to change ownership back to repo @MohitNSamagra

**Comment by karntrehan** [comment]
Flow: 
1. User lands on classroom link
2. Enrolls for classroom 
3. Repo with format stylusdb-sql-assignment-$user_name gets created under https://github.com/status-20X org. 
4. Github API tells us grading for each of these repos through github actions. 

Total forks: 1.7K
Forks visible in status-20X org: 1.4K

Issues:
1. In the video shared we have asked folks to transfer ownership of the created repo to their profile. These transferred repos' grading is not exposed to us by github. Impact: 108/1.7K (7.7%)
2. Contributors are forking the above created repositories to their profiles. This can be ignored.  Impact: 41/1.4K (2.9%).
 
Solutions: 
1. Upload corrected video which cuts at 7:03 (before asking people to transfer ownership)
2. Make 108 users contributors in status-20X org. Ask them to transfer repo to status-20X org from their profile. Users to re-run autograding on these transferred back repos.

**Comment by MohitNSamagra** [comment]
- @MohitNSamagra to follow up

**Comment by karntrehan** [comment]
PT confirmed that fix is working. No further issues. 
Certificate generation pending on @KDwevedi + @karntrehan

**Comment by MohitNSamagra** [comment]
- Certificate generation pending @KDwevedi @karntrehan
