### ISSUE TITLE
[Discord] Issue- Query ticketing third party bot limit reached

### ISSUE THREAD

**Issue by omkar309** [Code4GovTech/server#68]
**Requirement:**
@KDwevedi to assess if we need to change bot, delete previous tickets or get the paid version to remove limit.

**Reason:**
High traffic is expected on discord server and many queries will be raised. Limit will cause problems for contributors as well as PT to resolve them.

**Comment by KDwevedi** [comment]
The bot currently allows 50 live queries
The limit isn't arbitrary, it arises from the fact that discord allows 50 channels per category (as mentioned under GUILD_CATEGORY [here](https://discord.com/developers/docs/resources/channel#channel-object-channel-types))

Possible ways forward: 
- **manage queries better** : use `/close` to close queries after answering so the count remains below 50
- create additional categories

**Comment by karntrehan** [comment]
Vedant to ensure PT is closing tickets post resolution.
