### ISSUE TITLE
[DevOps] Deployment of DMP Management System

### ISSUE THREAD

**Issue by karntrehan** [Code4GovTech/server#77]
Deployment of Server, Flask App and cron job via Devops pipeline.

**Comment by karntrehan** [comment]
@VedantKhairnar and @sasi2312 to share repo links here.

**Comment by VedantKhairnar** [comment]
Repos:
- [DMP CMS Backend CRON Repo](https://github.com/Code4GovTech/DMP-CMS-Backend-CRON)
- [DMP CMS Backend API Repo](https://github.com/Code4GovTech/DMP-CMS-Backend-API)

**Comment by MohitNSamagra** [comment]
- Backend API repo done
- DMP frontend documentation done
- Cronjob in progress

**Comment by MohitNSamagra** [comment]
- To be updated after speaking to Tushar

**Comment by MohitNSamagra** [comment]
- cronjob deployed
