### ISSUE TITLE
Community Platform 2.0 - Phase 1

### ISSUE THREAD

**Issue by karntrehan** [Code4GovTech/server#79]
**Product Scope:** https://docs.google.com/spreadsheets/d/1-S6WpjYnQw3yrCysHcUr0WSHEL55C5HpI77RRG9DgS0/edit?gid=0#gid=0

**General Flow**

As a user, I am able to view advisory/design/mentor required projects, and I am able to apply, get selected and complete these projects.

**Acceptance Criteria**

- Relevant tag is picked from the issue ticket labels
- A filter can help me filter out the tickets I want to view on the website
- For all projects I am still redirected to GitHub issues- All details can be viewed in the issue ticket on GitHub
- If I want to apply as an advisor/designer/etc, I can click on the ticket and I will be redirected to the issue on GitHub which will have a Google form which will allow me to apply. If applications have closed, the Google Form will not be accepting responses.
- Post selection my github ID is added to the issue ticket description
- Post finishing of task, issue to be closed by the org which will reward all relevant assigned users with points.
- If accepted, the relevant number of points can be awarded to me as the user

**Tech Scoping:** #78 

BE changes: 
- [x] Understand current working of webhook API 
- [x] ~On specific label, trigger our new flow~ All tickets with 'C4GT Community' label to go through the new flow
- [x] Setup staging db on supabase.
- [x] Update database structure with[ this structure](https://github.com/Code4GovTech/server/issues/78#issuecomment-2167778540).
- [x] Get issue updates from webhook API when label is added and description is edited 
- [x] Pull labels, complexity, skills, technology from issue and save to db
- [x] Basis labels, identify needs of the issue: Advisor needed, Designer needed, Mentor needed, Contributor needed.
- [x] Take out Contributor, Designer, Coder, Advisor githubId from edited description and save to db
- [x] Get webhook update when ticket is closed
- [x] Point matrix table creation and updation
- [x] Pull contributors, issue details & points matrix from DB when issue is closed
- [x] Award points to users on issue closure - Points transactions and user points.
- [x] Record activity in activity table - Assigned, closed, awarded, etc.
- [x] Add handling for comments and PR creations. (currently hacked through script)
- [x] Create staging bot for testing 
- [x] Move from supabase queries to postgres queries

P1
- [ ] Generate badges when points awarded
- [ ] Generate certificates when points awarded

Web site changes:

_Designs needed for below_

- [ ] Pull labels, complexity, skills, technology from DB of issue and display it 
- [ ] Make issue element expandable with more details

**Comment by MohitNSamagra** [comment]
- To be picked from 20th Jun

**Comment by MohitNSamagra** [comment]
- https://docs.google.com/spreadsheets/d/1PO3tyD0txbU0AFKKWSZCP3-WQxT5TTxvrxOVXERQBV0/edit?gid=0#gid=0
- Current db audit + tables creation to be done

**Comment by karntrehan** [comment]
Blocked on https://github.com/Code4GovTech/DMP-CMS-Backend-API/issues/19

**Comment by MohitNSamagra** [comment]
- Deployment of github app tech pending - open question on when it should be done @karntrehan - TBD

**Comment by jaanbaaz** [comment]
@karntrehan and @MohitNSamagra what is the new flow in point number 2?

**Comment by MohitNSamagra** [comment]
- Staging db on supabase reinitiated

**Comment by MohitNSamagra** [comment]
1. once issue closed how can we provide points ?
2. Is point metrics and point_system are same in supabase ?
3. Currently how datas are created to contributor registeration ?
4. If im the person going to solve this issue means ...my details must be in contributor resgitration table right ?

**Comment by MohitNSamagra** [comment]
Scope review on Friday, 3:30

**Comment by MohitNSamagra** [comment]
- badges creation - in progress @sasi2312 
- pull labels, contributor lists - @jaanbaaz

**Comment by MohitNSamagra** [comment]
Takeways from labels PS:

- 3 different issue templates to be made(for design, coding, and advisory), using which labels will be added automatically
- Design and coding tickets have mentor fields using - mentor points to be given using this - what happens if multiple ids are mentioned?
- Redesign of db table to be discussed with @karntrehan - mentor points not considered

**Comment by karntrehan** [comment]
PT calls: 

- [ ] Labels to be used to run this flow
- [ ] ContributorId to be assignee or from description.

**Comment by MohitNSamagra** [comment]
- points_mapping table to reviewed @MohitNSamagra @karntrehan

**Comment by MohitNSamagra** [comment]
Pausing for other fixes in 2415

**Comment by MohitNSamagra** [comment]
- to be picked today

**Comment by MohitNSamagra** [comment]
- to be picked today

**Comment by jaanbaaz** [comment]
- @jaanbaaz to talk to @KDwevedi about c4gt-server-bot and then continue on it.

**Comment by karntrehan** [comment]
Making badges and certificates to P1. To be picked later. 

Rest to be closed today and sent for testing.

**Comment by MohitNSamagra** [comment]
- Ready to deploy - @KDwevedi to assist

**Comment by MohitNSamagra** [comment]
- Staging deployment to be done with @KDwevedi 
- Testing - Testing repo - issues will be created and closed and points will be awarded accordingly

**Comment by MohitNSamagra** [comment]
**Frontend**

[C4GTNewUI 2.pdf](https://github.com/user-attachments/files/16962141/C4GTNewUI.2.pdf)

For mentor points, the following message to be added: _All mentor points are 1.5x the contributor points_

**Comment by karntrehan** [comment]
UI to be updated with final changes. UI dev to pick up next week. 
QA to test BE flows only. Postgres visibility to be fixed.

**Comment by MohitNSamagra** [comment]
[C4GT CB 2.pdf](https://github.com/user-attachments/files/17009679/C4GT.CB.2.pdf)

**Comment by AakashSatpute119** [comment]
### Bugs [Community v2 - Phase 1]: 

- [ ] 1. Unable to configure c4gt staging app public repos/repos from outside the organization.
- [ ] 2. Issue logs are created, but no issue record is found in the DB.

**Comment by MohitNSamagra** [comment]
- @jaanbaaz to add fixes made

**Comment by MohitNSamagra** [comment]
- FE almost closed - category filter to be added

**Comment by MohitNSamagra** [comment]
- assignee issue to be closed

**Comment by MohitNSamagra** [comment]
- Assignee issue closed
- FE category filter added - now waiting for API integration
- Testing being resumed

**Comment by MohitNSamagra** [comment]
- Staging not connected to DB
- PR raised - @karntrehan @singhalkarun to review and deploy

**Comment by MohitNSamagra** [comment]
**DB Tables**

- issue contributor - mapping of issue to contributor
- issue mentors - mapping of issue and mentors
- points transaction - points allotted contributors and mentors

**Comment by MohitNSamagra** [comment]
- Final API to be given for FE
- to be pushed to dev
- Testing and fixes to be closed by today/Fri

**Comment by MohitNSamagra** [comment]
- Points allotment + leaderboard to be demoed by @jaanbaaz

**Comment by MohitNSamagra** [comment]
**UAT**

- Subcategory within template
- Internal mentors and allotment of points to them
